name: Build Tailwind CSS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci || npm i

      - name: Build Tailwind (v3)
        run: npx tailwindcss -i ./input.css -o ./output.css --minify

      - name: Upload output.css
        uses: actions/upload-artifact@v4
        with:
          name: output-css
          path: output.css
