name: Build Tailwind CSS

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # <-- importante para poder hacer commit

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci || npm i

      - name: Ensure dist folder
        run: mkdir -p dist

      - name: Build Tailwind (v3)
        run: npx tailwindcss -i ./input.css -o ./dist/output.css --minify

      - name: Commit built CSS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/output.css
          git commit -m "Build CSS from ${{ github.sha }}" || echo "No changes to commit"
          git push
